
FROM php:8.1

# Install system dependencies
RUN apt-get update \
    && apt-get install -y \
        libonig-dev \
        libzip-dev \
        unzip \
        libpq-dev \
        libcurl4-gnutls-dev \
    && rm -rf /var/lib/apt/lists/*

#  RUN apt-get update -y
#RUN docker-php-ext-install pdo pdo_mysql
#RUN apt-get install -y unzip libpq-dev libcurl4-gnutls-dev


# Install PHP extensions
RUN docker-php-ext-install pdo pdo_mysql zip

# Set working directory
WORKDIR /var/www

# Copy the application files
COPY . .

# Install Composer
#COPY --from=composer:2.5.7 /usr/bin/composer /usr/bin/composer

#RUN composer install
ENV COMPOSER_HOME /composer
ENV PATH ./vendor/bin:/composer/vendor/bin:$PATH
ENV COMPOSER_ALLOW_SUPERUSER 1
RUN curl -s https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin/

#RUN composer global require "squizlabs/php_codesniffer=*"

# Set the port for the Laravel application
ENV PORT=8000



# Set the entrypoint script
#ENTRYPOINT ["backend/Docker/entrypoint.sh"]

#COPY backend/Docker/entrypoint.sh /backend/Docker/entrypoint.sh
#RUN chmod +x /backend/Docker/entrypoint.sh